spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/intershop
    username: postgres
    password: serik1995

  liquibase:
    url: jdbc:postgresql://localhost:5432/intershop
    user: postgres
    password: serik1995
    driver-class-name: org.postgresql.Driver
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  sql:
    init:
      mode: never
